export const SHEDULE_FOR_STUDENTS = [
  {
    grade: "VIIIA",
    monday: [
      "Computer Science",
      "Biology",
      "Psychology",
      "Business",
      "Physics",
    ],
    tuesday: [
      "Physical Culture",
      "History",
      "Literature",
      "Higher Mathematics",
      "Astronomy",
    ],
    wednesday: [
      "Economy",
      "Engineering",
      "Philosophy",
      "Computer Science",
      "Social Sciences",
    ],
    thursday: [
      "Biology, Psychology",
      "Art",
      "Business, Physics",
      "Сhemistry",
      "Computer Science",
    ],
    friday: [
      "Сhemistry",
      "Higher Mathematics",
      "Philosophy",
      "Astronomy",
      "Engineering",
    ],
    saturday: ["Day off"],
  },

  {
    grade: "VIIIB",
    monday: [
      "Biology, Psychology",
      "Business, Physics",
      "Computer Science",
      "History",
      "Physical Culture",
    ],
    tuesday: [
      "Сhemistry",
      "Higher Mathematics",
      "Philosophy",
      "Astronomy",
      "Engineering",
    ],
    wednesday: [
      "Biology, Psychology",
      "Art",
      "Business, Physics",
      "Сhemistry",
      "Computer Science",
    ],
    thursday: [
      "Economy",
      "Engineering",
      "Philosophy",
      "Computer Science",
      "Social Sciences",
    ],
    friday: [
      "Computer Science",
      "Biology",
      "Psychology",
      "Business",
      "Physics",
    ],
    saturday: ["Day off"],
  },
  {
    grade: "VIIIC",
    monday: [
      "Astronomy",
      "Psychology",
      "Philosophy",
      " Art",
      "Higher Mathematics",
    ],
    tuesday: [
      "Engineering",
      "Literature",
      "Physics",
      "Physical Culture",
      "Economy",
    ],
    wednesday: [
      "History",
      "Biology",
      "Computer Science",
      "Social Sciences",
      "Сhemistry",
    ],
    thursday: [
      "Business",
      "Physical Culture",
      "Engineering",
      "Philosophy",
      "Psychology",
    ],
    friday: ["Social Sciences", "Literature", "Physics", "Economy", "Biology"],
    saturday: ["Day off"],
  },
  {
    grade: "IXA",
    monday: ["Business", "History", "Art", "Literature", "Computer Science"],
    tuesday: ["Economy", "Psychology", "Physics", "Philosophy", "Biology"],
    wednesday: [
      "Social Sciences",
      "Physical Culture",
      "Engineering",
      "Astronomy",
      "Higher Mathematics",
    ],
    thursday: ["Сhemistry", "Business", "Engineering", "Physics", "Biology"],
    friday: ["Psychology", "Philosophy", "Social Sciences", "Art", "Сhemistry"],
    saturday: ["Day off"],
  },
  {
    grade: "IXB",
    monday: [
      "Economy",
      "Computer Science",
      "Astronomy",
      "Literature",
      "Higher Mathematics",
    ],
    tuesday: ["Economy", "Social Sciences", "History", "Philosophy", "Art"],
    wednesday: [
      "Physical Culture",
      "Literature",
      "Business",
      "Сhemistry",
      "Psychology",
    ],
    thursday: [
      "Biology",
      "Higher Mathematics",
      "Engineering",
      "Physics",
      "Astronomy",
    ],
    friday: [
      "Psychology",
      "Philosophy",
      "Computer Science",

      "Art",
      "Сhemistry",
    ],
    saturday: ["Day off"],
  },
  {
    grade: "IXC",
    monday: ["Business", "Astronomy", "Engineering", "Biology", "Psychology"],
    tuesday: [
      "Art",
      "Social Sciences",
      "Literature",
      "Computer Science",
      "Physics",
    ],
    wednesday: [
      "Philosophy",
      "Сhemistry",
      "Economy",
      "Physical Culture",
      "Higher Mathematics",
    ],
    thursday: [
      "Psychology",
      "Philosophy",
      "Computer Science",
      "Art",
      "Сhemistry",
    ],
    friday: [
      "Higher Mathematics",
      "Engineering",
      "Physics",
      "Astronomy",
      "History",
    ],
    saturday: ["Day off"],
  },
  {
    grade: "XA",
    monday: [
      "Physical Culture",
      "History",
      "Literature",
      "Higher Mathematics",
      "Astronomy",
    ],
    tuesday: [
      "Computer Science",
      "Biology",
      "Psychology",
      "Business",
      "Physics",
    ],
    wednesday: [
      "Сhemistry",
      "Higher Mathematics",
      "Philosophy",
      "Astronomy",
      "Engineering",
    ],
    thursday: [
      "Biology, Psychology",
      "Art",
      "Business, Physics",
      "Сhemistry",
      "Computer Science",
    ],
    friday: [
      "Economy",
      "Engineering",
      "Philosophy",
      "Computer Science",
      "Social Sciences",
    ],
    saturday: ["Day off"],
  },

  {
    grade: "XB",
    monday: [
      "Economy",
      "Engineering",
      "Philosophy",
      "Computer Science",
      "Social Sciences",
    ],
    tuesday: [
      "Сhemistry",
      "Higher Mathematics",
      "Philosophy",
      "Astronomy",
      "Engineering",
    ],
    wednesday: [
      "Computer Science",
      "Biology",
      "Psychology",
      "Business",
      "Physics",
    ],
    thursday: [
      "Biology, Psychology",
      "Business, Physics",
      "Computer Science",
      "History",
      "Physical Culture",
    ],
    friday: [
      "Biology, Psychology",
      "Art",
      "Business, Physics",
      "Сhemistry",
      "Computer Science",
    ],
    saturday: ["Day off"],
  },
  {
    grade: "XC",
    monday: [
      "Engineering",
      "Literature",
      "Physics",
      "Physical Culture",
      "Economy",
    ],
    tuesday: [
      "Astronomy",
      "Psychology",
      "Philosophy",
      " Art",
      "Higher Mathematics",
    ],
    wednesday: [
      "Business",
      "Physical Culture",
      "Engineering",
      "Philosophy",
      "Psychology",
    ],
    thursday: [
      "History",
      "Biology",
      "Computer Science",
      "Social Sciences",
      "Сhemistry",
    ],
    friday: ["Social Sciences", "Literature", "Physics", "Economy", "Biology"],
    saturday: ["Day off"],
  },
  {
    grade: "XIA",
    monday: [
      "Astronomy",
      "Psychology",
      "Philosophy",
      " Art",
      "Higher Mathematics",
    ],
    tuesday: [
      "History",
      "Biology",
      "Computer Science",
      "Social Sciences",
      "Сhemistry",
    ],
    wednesday: [
      "Economy",
      "Engineering",
      "Philosophy",
      "Computer Science",
      "Social Sciences",
    ],
    thursday: [
      "Computer Science",
      "Biology",
      "Psychology",
      "Business",
      "Physics",
    ],
    friday: ["Biology", "Art", "Business", "Сhemistry", "Computer Science"],
    saturday: ["Day off"],
  },

  {
    grade: "XIB",
    monday: ["Biology", "Economy", "Engineering", "Philosophy", "Engineering"],
    tuesday: [
      "Computer Science",
      "Social Sciences",
      "Philosophy",
      "Economy",
      "Astronomy",
    ],
    wednesday: [
      "Art",
      "Social Sciences",
      "Psychology",
      "Astronomy",
      "Higher Mathematics",
    ],
    thursday: ["Physics", "Literature", "Biology", "Engineering", "Philosophy"],
    friday: [
      "Business",
      "Computer Science",
      "Сhemistry",
      "Physical Culture",
      "History",
    ],
    saturday: ["Day off"],
  },
  {
    grade: "XIC",
    monday: [
      "Computer Science",
      "Biology",
      "Engineering",
      "Literature",
      "Physics",
    ],
    tuesday: ["Astronomy", "Psychology", "Art", "Physical Culture", "Economy"],
    wednesday: [
      "Literature",
      "Astronomy",
      "Philosophy",
      "Physical Culture",
      "Social Sciences",
    ],
    thursday: ["Physics", "Business", "Engineering", "History", "Сhemistry"],
    friday: [
      "Psychology",
      "Economy",
      "Higher Mathematics",
      "Computer Science",
      "Biology",
    ],
    saturday: ["Day off"],
  },
];
